
POST http://localhost:6868/register
Content-Type: application/json

{
    "phoneNumber": "1234567",
    "password": "thaithuytb",
    "roomID": 3,
    "isAdmin": false
}

###
POST http://localhost:6868/login
Content-Type: application/json

{
    "phoneNumber": "0384560432",
    "password": "thaithuytb"
}
###
POST http://localhost:6868/updateUser
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ4MjgyOTg2LCJleHAiOjE2NDgyODY1ODZ9.h1RM_sRJb6S10IyWkevl9809AdKeNl_W0tJTGPCu-WE
Content-Type: application/json

{
    "fullName": "Thaingoo",
    "cardNumber": 12345678,
    "sex": "female",
    "dateOfBirth": "2001-11-29T16:50:50.844Z"
}

###
GET http://localhost:6868
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ4MTEyMTE3LCJleHAiOjE2NDgxMTU3MTd9.DBr7s0gU0059hRxPa5fWQVMfuzKTDVoV4QabKiStl8M

###
POST http://localhost:6868/changePW
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ4MDE4NzU2LCJleHAiOjE2NDgwMjIzNTZ9.-egA1ucecENWw_cjo5ZB1SvVdQ9Zz1peBuIiED7cuKw
Content-Type: application/json

{
    "password": "thaithuytb",
    "newPassword": "thaithuy"
}

###

GET http://localhost:6868/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODMyNjczLCJleHAiOjE2NDc4MzYyNzN9.Yc_U5T97Mb0FC-pkA_hgsbaNZUm5TluBVbZETsP5X_A
###
GET http://localhost:6868/detailUser
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ4Mjg2OTA3LCJleHAiOjE2NDgyOTA1MDd9.pUBugW4YKw0QAhVHteekiDZp1vcpSrzFJZbAwiHlck8

###

GET http://localhost:6868/room/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ4MzY4NDQyLCJleHAiOjE2NDgzODY0NDJ9.FFogPBDkxvbbsMXMPXKoffgFpVG2bogyBWsUzVOOEw4

###
GET http://localhost:6868/room
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjQ4MTEzOTkzLCJleHAiOjE2NDgxMTc1OTN9.hskktT-EnkOSMEnMCzQyOOqsUFYwbYuNkFNcyCv0KHU

###

POST http://localhost:6868/room
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODgwNjE2LCJleHAiOjE2NDc4ODQyMTZ9.srNIGMUMQ3moziQWpZHKyMHvW4vB0bK1paAU32yUvmY
Content-Type: application/json

{
    "roomName": "c6",
    "rentPrice": 3500000,
    "isEmpty": true,
    "haveWifi": true
}

###
PUT http://localhost:6868/room/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODgwNjE2LCJleHAiOjE2NDc4ODQyMTZ9.srNIGMUMQ3moziQWpZHKyMHvW4vB0bK1paAU32yUvmY
Content-Type: application/json

{
    "roomName": "c3.3",
    "rentPrice": 2000000,
    "isEmpty": true,
    "haveWifi": true
}

###
DELETE  http://localhost:6868/room/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODM3Njc3LCJleHAiOjE2NDc4NDEyNzd9.mwWOvqGEwzaO7bfgnFN5ilPQpqN1u_qlk1Mq2AEEoOE
Content-Type: application/json

###
GET http://localhost:6868/bill/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ4MzY4NDQyLCJleHAiOjE2NDgzODY0NDJ9.FFogPBDkxvbbsMXMPXKoffgFpVG2bogyBWsUzVOOEw4
