
POST http://localhost:6969/register
Content-Type: application/json

{
    "phoneNumber": "03845604325",
    "password": "thaithuytb",
    "roomID": 4,
    "isAdmin": false
}

###
POST http://localhost:6969/login
Content-Type: application/json

{
    "phoneNumber": "03845604320",
    "password": "thaithuytb"
}

###

GET http://localhost:6969/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODMyNjczLCJleHAiOjE2NDc4MzYyNzN9.Yc_U5T97Mb0FC-pkA_hgsbaNZUm5TluBVbZETsP5X_A
###
GET http://localhost:6969/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjQ3Nzk0MTMyLCJleHAiOjE2NDc3OTc3MzJ9.TQ8KkI6Ahb8kRsAenmhnR72euQC718zjp8BZKINBjps

###

GET http://localhost:6969/room/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODgwNjE2LCJleHAiOjE2NDc4ODQyMTZ9.srNIGMUMQ3moziQWpZHKyMHvW4vB0bK1paAU32yUvmY

###
GET http://localhost:6969/room
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODgwNjE2LCJleHAiOjE2NDc4ODQyMTZ9.srNIGMUMQ3moziQWpZHKyMHvW4vB0bK1paAU32yUvmY

###

POST http://localhost:6969/room
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODgwNjE2LCJleHAiOjE2NDc4ODQyMTZ9.srNIGMUMQ3moziQWpZHKyMHvW4vB0bK1paAU32yUvmY
Content-Type: application/json

{
    "roomName": "c6",
    "rentPrice": 3500000,
    "isEmpty": true,
    "haveWifi": true
}

###
PUT http://localhost:6969/room/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODgwNjE2LCJleHAiOjE2NDc4ODQyMTZ9.srNIGMUMQ3moziQWpZHKyMHvW4vB0bK1paAU32yUvmY
Content-Type: application/json

{
    "roomName": "c3.3",
    "rentPrice": 2000000,
    "isEmpty": true,
    "haveWifi": true
}

###
DELETE  http://localhost:6969/room/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ3ODM3Njc3LCJleHAiOjE2NDc4NDEyNzd9.mwWOvqGEwzaO7bfgnFN5ilPQpqN1u_qlk1Mq2AEEoOE
Content-Type: application/json
